services:
  - type: web
    name: xsmb
    env: php
    buildCommand: "npm install && npm run build && composer install --optimize-autoloader --no-dev"
    startCommand: "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT & php artisan xsmb:live-watch --force"
